import './globals.css'
import { AuthContextProvider } from './context/authContext'

const links = [{
  label: "Home",
  route: '/',
}, {
  label: "Login",
  route: '/login',
}]

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AuthContextProvider>
          {children}
        </AuthContextProvider>
      </body>
    </html>
  )
}
